---
new_page_extension: md
auto_deploy: false
admin_path: ".forestry"
webhook_url: 
sections:
- type: heading
  label: Contenido
- type: directory
  path: src/pages
  label: Páginas
  create: all
  match: "**/*.md"
  exclude: "{_includes,_data,admin,static}/**/*"
  new_doc_ext: md
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - post
- type: document
  path: src/_data/authors.yml
  label: Autores
- type: document
  path: src/_data/tags.yml
  label: Etiquetas
- type: heading
  label: Configuraciones
- type: document
  path: src/_data/navigation.yaml
  label: Navegación
- type: document
  path: src/_data/settings.yaml
  label: Configuración
upload_dir: src/static/img
public_path: "/static/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
